kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: kcd-lima-app
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  to:
    kind: Service
    name: kcd-lima-app
    weight: 100
  port:
    targetPort: 8080

