apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id}}-dev
  {%- if values.description %}
  description: ${{values.description}}
  {%- endif %}
  annotations:
    argocd/app-name: ${{values.component_id}}-dev
    argocd/app-namespace: argocd
    argocd/instance-name: kind-local
    backstage.io/kubernetes-id: ${{values.component_id}}
    backstage.io/kubernetes-namespace: ${{values.namespace}}
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ${{values.githubOrg}}/${{values.repoName}}
  tags:
    - java
    - quarkus
    - maven
    - kcd-lima
  links:
    - url: https://github.com/${{values.githubOrg}}/${{values.repoName}}
      title: Source repository
      icon: github
spec:
  type: service
  lifecycle: production
  owner: ${{values.owner | dump}}
