apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app: kcd-lima-app
    app.kubernetes.io/component: kcd-lima-app
    app.kubernetes.io/instance: kcd-lima-app
    app.kubernetes.io/name: kcd-lima-app
    app.kubernetes.io/part-of: kcd-lima-app
    app.openshift.io/runtime-version: 1.0.0
  name: kcd-lima-app
spec:
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: kcd-lima-app
    weight: 100
  wildcardPolicy: None